# This is a basic workflow to help you get started with Actions

name: Build binaries

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache Electron binaries
        uses: actions/cache@v2
        env:
          cache-name: cache-electron-bins
        with:
        # cache location is described here:
        # https://github.com/electron/get#how-it-works
          path: ~/.cache/electron
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup npm
        run: sudo npm i -g npm@7
      - name: Install build deps
        run: npm install
      - name: Build
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: Linux-AppImages
          path: dist/*.AppImage
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-Installer
          path: dist/*.exe
          if-no-files-found: error
      - uses: actions/upload-artifact@v2
        with:
          name: MacOS-Image
          path: dist/*.dmg
          if-no-files-found: error
