name: Publish

on:
  release:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: 'build:github'
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows-x64-Installer
          path: dist/*.exe
          if-no-files-found: error
      - name: Publish
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            *.exe
      
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: 'build:github'
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux-x64-deb
          path: dist/*.deb
          if-no-files-found: error
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux-x64-AppImage
          path: dist/*.AppImage
          if-no-files-found: error
      - name: Publish
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            *.deb
            *.AppImage

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: 'build:github'
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: MacOS-Image
          path: dist/*.dmg
          if-no-files-found: error
      - name: Publish
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            *.dmg

  linux-unpacked:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: npm
        run: |
          npm install
          npm run pack
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Linux-Unpacked
          path: dist/linux-unpacked
          if-no-files-found: error
      - name: Publish
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            *.*

  windows-unpacked:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: npm
        run: |
          npm install
          npm run pack
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows-Unpacked
          path: dist/win-unpacked
          if-no-files-found: error
      - name: Publish
        uses: SierraSoftworks/gh-releases@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            *.*
